### ISSUE TITLE
Need Help regarding Xposed

### ISSUE THREAD

**Issue by araafroyall** [LiAlH4-Tr/LDF#1]
hi. i am a developer of https://github.com/araafroyall/Cleaner-Pro-Lite

i want to enable xposed features in it. but i dont know about xposed implimentation. 
i made this using sketchware. 
can you help , how to make xposed implimentation using sketchware pro

**Comment by LiAlH4-Tr** [comment]
In my knowledge, you are advised to learn Java, since writing Xposed module requires using Java API provided by Xposed. Or you can try to find if Sketchware can let you communicate with custom Java interface or not, but I think it doesn't and Sketchware generated app has less possibility to be identified as a module by Xposed.

**Comment by araafroyall** [comment]
sketchware pro has such compatibility to add custom java codes etc..

but i dont know what should i need to add or do so my app detected as xposed module
